# Generated by Django 3.0 on 2020-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200622_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='end_date',
            field=models.DateField(default='2023-10-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateField(default='2023-09-20'),
            preserve_default=False,
        ),
    ]
