# Generated by Django 3.0 on 2020-06-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200622_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='duration',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='end_time',
            field=models.TimeField(default='12:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='start_time',
            field=models.TimeField(default='9:00', max_length=100),
            preserve_default=False,
        ),
    ]
